name: "Laravel Pint"


on:
  push:
    branches: 
      - main


jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.2.2
        ports:
          - 6379:6379
      
      mysql:
        image: mysql:8.0        
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: project7
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
        with: 
          ref: ${{ github.head_ref }}

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: vendor/

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.35.5
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push Changes Back to Repo
        run: |
          git config user.name "dhan"
          git config user.email "dhan@fueledbyweb.com"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push