name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.2.2
        ports:
          - 6379:6379
      
      mysql:
        image: mysql:8.0        
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: project7
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    env: 
      PHP_VERSION: '8.3'
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, xml, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
      CACHE_KEY: extension-cache-v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact
