name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.2.2
        ports:
          - 6379:6379
      
      mysql:
        image: mysql:8.0        
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: project7
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Get Composer cache dir
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4.3.0
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.35.5
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact
