name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.2.2
        ports:
          - 6379:6379
      
      mysql:
        image: mysql:8.0        
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: project7
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact --coverage --min=75
